name: Run k6 Cloud Test

on:
  schedule:
      - cron: '0 7 * * *' # Runs every day at 7 AM
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  k6-cloud-test:
    name: Run k6 test on Grafana Cloud
    runs-on: ubuntu-latest
    env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
          MY_HOSTNAME: ${{ secrets.APP_HOSTNAME }}
          MY_BROWSER_HOSTNAME: ${{ secrets.APP_BROWSER_HOSTNAME }}
          TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
        with:
          browser: true

      - name: Run k6 performance tests
        uses: grafana/run-k6-action@v1
        with:
          path: |
            ./scripts/api/order/submit-and-retrieve-order.js
            ./scripts/browser/*
          cloud-comment-on-pr: true