name: Run k6 Cloud Test

on:
  schedule:
      - cron: '0 7 * * *' # Runs every day at 7 AM
  workflow_dispatch:

jobs:
  k6-cloud-test:
    name: Run k6 test on Grafana Cloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run k6 cloud test
        uses: grafana/run-k6-action@v1
        with:
          path: ./scripts/api/order/submit-and-retrieve-order.js
          cloud-comment-on-pr: true
          # Virtual users set to 3
          # Duration set to 5 minutes
          flags: --vus 3 --duration 5m

        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}
          MY_HOSTNAME: ${{ secrets.APP_HOSTNAME }}
          USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
