name: Run k6 Cloud Test - Browser

on:
  schedule:
      - cron: '0 7 * * *' # Runs every day at 7 AM
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  k6-cloud-test:
    name: Run k6 test on Grafana Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup K6
        uses: grafana/setup-k6-action@v1
        with:
          browser: true

      - name: Run k6 Browser tests
        uses: grafana/run-k6-action@v1
        with:
          path: ./scripts/browser/*
          cloud-comment-on-pr: true
        env:
          MY_HOSTNAME: ${{ secrets.APP_BROWSER_HOSTNAME }}
          K6_BROWSER_NO_SANDBOX: true
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
          K6_CLOUD_PROJECT_ID: ${{ secrets.K6_CLOUD_PROJECT_ID }}